### PR TITLE
Updates header for reference genbank file.

### PR DESCRIPTION
**Pull request by cassiawag**
This resolves issue #9 by updating `create_ref_genome.py`

### CODE REVIEW

**Comment by trvrb** [comment]
@cassiawag ---

This is producing the following top-matter:
```
LOCUS       A/Beijing/32/1992      13350 bp    DNA              VRL 01-JAN-1980
DEFINITION  Influenza A virus (A/Beijing/32/1992(H3N2)).
ACCESSION   Influenza A virus (A/Beijing/32/1992(H3N2))
VERSION     Influenza A virus (A/Beijing/32/1992(H3N2))
```
Can you revise so it produces:
```
LOCUS       A/Beijing/32/1992      13350 bp    DNA              VRL 01-JAN-1980
DEFINITION  A/Beijing/32/1992
ACCESSION   A/Beijing/32/1992
VERSION     A/Beijing/32/1992
```
Likewise, H1N1pdm is producing:
```
LOCUS       A/Cali/07/2009         13417 bp    cRNA    linear   VRL 01-JAN-1980
DEFINITION  Influenza A virus (A/California/07/2009(H1N1)).
ACCESSION   Influenza A virus (A/California/07/2009(H1N1))
VERSION     Influenza A virus (A/California/07/2009(H1N1))
```
Can you revise to:
```
LOCUS       A/Cali/07/2009         13417 bp    cRNA    linear   VRL 01-JAN-1980
DEFINITION  A/California/07/2009
ACCESSION   A/California/07/2009
VERSION     A/California/07/2009
```

You can either grab `A/Beijing/32/1992` / `A/California/07/2009` from an argument passed into `create_ref_genome.py` or from the `strain` field for the Genbank file.

Thank you!

**Review by trvrb — CHANGES_REQUESTED** [review]
Please see comment above.

**Comment by cassiawag** [comment]
@trvrb; This should produce the appropriate Locus, Definition, Version, and Accession values. I ended up passing in `reference_strain` as an argument into `create_ref_genome.py`. I had to pass it in as a parameter rather than input because Snakemake threw errors otherwise. Thanks for the patience.

**Review by trvrb — APPROVED** [review]
This looks great! Thanks @cassiawag.

**Pull request merged**
